from __future__ import annotations

"""Export frozen replay recognizer banks as a C++ header.

The generated header is data only. It never grants runtime authority; the input
JSON banks must explicitly declare `runtime_authorized=false`. OpenHoldem can
therefore compile/test the exact same rank masks and suit prototypes without a
runtime JSON dependency or a second hand-maintained copy.
"""

import argparse
import json
from pathlib import Path


RANKS = list("23456789TJQKA")


def _load(path: Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("runtime_authorized") is not False:
        raise ValueError(f"{path} unexpectedly claims runtime authority")
    return data


def _validate_templates(entries: list[dict], *, name: str) -> None:
    if [entry["rank"] for entry in entries] != RANKS:
        raise ValueError(f"{name} must contain ranks 2..A exactly once in order")
    for entry in entries:
        rows = entry["rank_mask_rows"]
        if len(rows) != 24:
            raise ValueError(f"{name}/{entry['rank']} must have 24 rows")
        if any(not isinstance(row, int) or row < 0 or row >= (1 << 16) for row in rows):
            raise ValueError(f"{name}/{entry['rank']} contains invalid 16-bit row")


def _emit_template_array(lines: list[str], symbol: str, entries: list[dict]) -> None:
    _validate_templates(entries, name=symbol)
    lines.append(f"static const COFCRankTemplate {symbol}[13] = {{")
    for entry in entries:
        rows = ", ".join(str(int(row)) for row in entry["rank_mask_rows"])
        source = entry.get("source_frame", "unknown")
        slot = entry.get("slot_index", "-")
        card = entry.get("source_card", "-")
        lines.append(f"  // {entry['rank']} <- {card} {source} slot={slot}")
        lines.append(f"  {{'{entry['rank']}', {{{rows}}}}},")
    lines.append("};")
    lines.append("")


def export_header(fan_bank: dict, upright_bank: dict) -> str:
    fan_entries = fan_bank["rank_templates"]
    upright_large = upright_bank["large"]
    upright_small = upright_bank["small"]

    fan_prototypes = fan_bank["extraction"]["suit_prototypes"]
    required_suits = ["c", "d", "h", "s"]
    if sorted(fan_prototypes) != required_suits:
        raise ValueError("fan bank must contain c/d/h/s suit prototypes")

    fan_match = fan_bank["extraction"]["rank_match"]
    suit_match = fan_bank["extraction"]["suit_match"]

    lines = [
        "// AUTO-GENERATED by DeepOFC/tools/export_fantasy_recognizer_cpp.py",
        "// Source banks are replay calibration artifacts and DO NOT grant runtime authority.",
        "#ifndef INC_DEEPOFC_FANTASY_RECOGNIZER_BANKS_GENERATED_H",
        "#define INC_DEEPOFC_FANTASY_RECOGNIZER_BANKS_GENERATED_H",
        "",
        "#include \"COFCFantasyRecognitionCore.h\"",
        "",
        "static const bool kDeepOFCRecognizerBanksRuntimeAuthorized = false;",
        f"static const int kDeepOFCFanRankAlignmentPixels = {int(fan_match['max_translation_pixels'])};",
        f"static const double kDeepOFCFanRankMaxDistance = {float(fan_match['max_distance']):.17g};",
        f"static const double kDeepOFCFanRankMinMargin = {float(fan_match['min_margin']):.17g};",
        f"static const double kDeepOFCSuitMaxDistance = {float(suit_match['max_distance']):.17g};",
        f"static const double kDeepOFCSuitMinMargin = {float(suit_match['min_margin']):.17g};",
        "",
    ]

    _emit_template_array(lines, "kDeepOFCFantasy15FanRankTemplates", fan_entries)
    _emit_template_array(lines, "kDeepOFCUprightLargeRankTemplates", upright_large)
    _emit_template_array(lines, "kDeepOFCUprightSmallRankTemplates", upright_small)

    lines.append("static const COFCRgbPrototype kDeepOFCSuitPrototypes[4] = {")
    for suit in required_suits:
        rgb = [float(value) for value in fan_prototypes[suit]]
        lines.append(
            "  {'%s', %.17g, %.17g, %.17g}," % (suit, rgb[0], rgb[1], rgb[2])
        )
    lines.append("};")
    lines.append("")
    lines.append("#endif  // INC_DEEPOFC_FANTASY_RECOGNIZER_BANKS_GENERATED_H")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fan-bank", type=Path, required=True)
    parser.add_argument("--upright-bank", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    fan = _load(args.fan_bank)
    upright = _load(args.upright_bank)
    text = export_header(fan, upright)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8", newline="\n")
    print(args.out)


if __name__ == "__main__":
    main()
